<?php


namespace app\components;


use yii\base\Component;
use yii\caching\DbDependency;
use yii\caching\TagDependency;
use yii\db\Connection;
use yii\db\Exception;
use yii\db\Query;

class DaoComponent extends Component
{
    /** @var Connection */
    public $connection;

    public function init()
    {
        $this->connection=\Yii::$app->db;
        parent::init(); // TODO: Change the autogenerated stub
    }
//безопасный запрос через именованный маркер :user, передает параметр в виде массива [':user'=>$user_id]
    public function getActivityUser($user_id){
        $sql='select * from activity where user_id=:user';

        return $this->connection->createCommand($sql,[':user'=>$user_id])
            // использовать при сложном или часто повторяющемся запросе - в условии кеша записывается еще один запрос
            ->cache(10,new DbDependency(['sql' => 'select max(id)
            from activity where user_id='.(int)$user_id]))
            ->queryAll();

    }

    public function getFirstActivityBlocked(){
        $query=new Query();
        //сбрасываем кеш по тегу
       //TagDependency::invalidate(\Yii::$app->cache,'tag1');
        return $query->select(['id','title'])
            ->from('activity')
            ->andWhere(['isBlocked'=>1])
            ->orderBy(['title'=>SORT_DESC])
            //к запросам привязываем тег; весь кеш, помеченный этим тегом - сбрасывается
            ->cache(10,new TagDependency(['tags' => 'tag1']))
            ->one($this->connection);
    }

    public function getCountActivity(){
        $query=new Query();
        return $query->from('activity')
            ->select('count(id) as cnt')
//            ->join('inner join','users','activity.user_id=user.id')
            ->createCommand()->rawSql; //возвращает строку запроса sql - SELECT count(id) as cnt FROM `activity`
//            ->scalar($this->connection); //возвращает скалярное значение первого столбца первой строки результата.
    }
//здесь кеш не сработает, т.к. работает reader - забирает данные одного запроса маленькими порциями
    public function getBigData(){
        $query=new Query();
        return $query->select(['id','title'])
            ->from('activity')
            ->andWhere(['isBlocked'=>0])
            ->orderBy(['title'=>SORT_DESC])
            ->createCommand()->query();
    }

    public function insertsTransaction(){
//        $trans=$this->connection->beginTransaction();
//        try{
//            $this->connection->createCommand()
//                ->update('activity',['title'=>'new Task'],
//                    ['id'=>2])->execute();
//            throw new Exception('error');
//            $this->connection->createCommand()
//                ->update('activity',['title'=>'new Task'],
//                    ['id'=>2])->execute();
//
//            $trans->commit();
//        }catch (\Exception $e){
//            $trans->rollBack();
//        }

        //второй компактный способ транзакции
        $this->connection->transaction(function($db){
            $this->connection->createCommand()
                ->update('activity',['title'=>'new'],
                    ['id'=>2])->execute();
            //throw new Exception('error'); //намеренная ошибка
            $this->connection->createCommand()
                ->update('activity',['title'=>'new'],
                    ['id'=>2])->execute();
        });
    }

    public function getUsersAll(){
        $sql='SELECT * from users;';
        return $this->connection->createCommand($sql)
            //по времени 10 сек находится в кеш
            ->cache(10)
            ->queryAll();
    }

}