<?php


namespace app\base;


use yii\web\Controller;

class BaseWebController extends Controller
{
    public function beforeAction($action)
    {
        if(\Yii::$app->user->isGuest){
            throw new HttpException(401,'need auth'); //return $this->redirect('/auth/sign-up')
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function afterAction($action, $result)
    {
        \Yii::$app->session->setFlash('pageBack',\Yii::$app->request->pathInfo);
        return parent::afterAction($action, $result);
    }

}